title                   : "DigitalGov - Building the 21st Century Digital Government"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "digital.gov"
themesDir               : "./themes"

MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 100
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true

ignoreFiles:
  - "^_template"
  - "content/_tmp/*"
  - "content/images/*"
# uncomment the following for a dev mode that excludes posts before 2017
  - "content/posts/201[0-6]"

sitemap:
  changefreq            : "monthly"
  priority              : 0.5
  filename              : "sitemap.xml"

outputFormats:
  SiteImages:
    mediaType: "application/json"
    baseName: "siteimages"
    isPlainText: true
    notAlternative: true
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

rssLimit: 20

outputs:
  home: ["HTML","RSS", "SiteImages"]

blackfriday:
  fractions: false

params:
  description: "We’re building a modern government, together."
  cdnurl: "https://s3.amazonaws.com/digitalgov"
  devmode: true

permalinks:
  posts                 : ":year/:month/:day/:slug/"
  events                : "event/:year/:month/:day/:slug/"

taxonomies:
  tag                   : "tag"
  category              : "categories"
  author                : "authors"

menu:
  primary:
    - Name            : "Home"
      Identifier      : "home"
      URL             : "/*/"
      Weight          : 1

    - Name            : "Resources"
      Identifier      : "resources"
      URL             : "/resources/"
      Weight          : 2

    - Name            : "Training & Events"
      Identifier      : "events"
      URL             : "/events/"
      Weight          : 3

    - Name            : "communities"
      Identifier      : "communities"
      URL             : "/communities/"
      Weight          : 4

    - Name            : "About"
      Identifier      : "about"
      URL             : "/about/"
      Weight          : 5

    - Name            : "Join"
      Identifier      : "join"
      URL             : "/join/"
      Weight          : 6

  secondary:
    - Name            : "Challenges"
      Identifier      : "challenges"
      URL             : "/categories/challenges/"
    - Name            : "Crowdsourcing & Citizen Science"
      Identifier      : "crowdsourcing-and-citizen-science"
      URL             : "/categories/crowdsourcing-and-citizen-science/"
    - Name            : "code"
      Identifier      : "code"
      URL             : "/categories/code/"
    - Name            : "API"
      Identifier      : "api"
      URL             : "/categories/api/"
    - Name            : "Data"
      Identifier      : "data"
      URL             : "/categories/data/"
    - Name            : "content"
      Identifier      : "content"
      URL             : "/categories/content/"
    - Name            : "Video"
      Identifier      : "video"
      URL             : "/categories/video/"
    - Name            : "Writing"
      Identifier      : "writing"
      URL             : "/categories/writing/"
    - Name            : "managing digital"
      Identifier      : "managing-digital"
      URL             : "/categories/managing-digital/"
    - Name            : "Governance"
      Identifier      : "governance"
      URL             : "/categories/governance/"
    - Name            : "Strategy & Policy"
      Identifier      : "governance"
      URL             : "/categories/strategy-and-policy/"
    - Name            : "metrics"
      Identifier      : "resources"
      URL             : "/categories/metrics/"
    - Name            : "mobile"
      Identifier      : "mobile"
      URL             : "/categories/mobile/"
    - Name            : "social media"
      Identifier      : "social-media"
      URL             : "/categories/social-media/"
    - Name            : "ux"
      Identifier      : "ux"
      URL             : "/categories/ux/"
    - Name            : "Accessibility"
      Identifier      : "accessibility"
      URL             : "/categories/accessibility/"
    - Name            : "Design"
      Identifier      : "design"
      URL             : "/categories/design/"
    - Name            : "User Testing & Research"
      Identifier      : "user-testing-and-research"
      URL             : "/categories/user-testing-and-research/"

foobar:
  qaz           : "Bingo!"
